// src/packages/Monitor/components/Danmaku/templates/Default.vue
<template>
    <div :class="`item ${showAnimation?'fadeInLeft' : ''} ${getItemClass(data)}`">
        <!-- 等级 -->
        <span v-if="showLevel" :class="`item__level UserLevel ${mode==='night' && Number(data.lv < 70)?'fansLevelNight':''} UserLevel--${data.lv}`"></span>
        <!-- 贵族 -->
        <span v-if="!!data.noble && showNoble" class="item__noble Barrage-icon Barrage-noble">
            <img :src="`${data.noble in nobleData ? nobleData.prefix + nobleData[data.noble].pic : ''}`" loading="lazy"/>
        </span>
        <!-- 粉丝牌 -->
        <div v-if="!!data.fansName && showFans" :class="`item__fans ${!!data.diamond && showDiamond ? 'is-diamonds' : ''} FansMedal fansLevel-${data.fansLv}`">
            <span class="FansMedal-name">{{data.fansName}}</span>
            <img v-if="!!data.diamond && showDiamond" class="FansMedalBox-diamondsIcon" src="https://sta-op.douyucdn.cn/douyu/2021/08/05/02304a1c04587e43ac626ce5ce07d935.png" alt="" loading="lazy">
        </div>
        <span v-if="data.roomAdmin=='4' && showRoomAdmin" class="item__roomAdmin">
            <span class="Barrage-icon Barrage-icon--roomAdmin"></span>
        </span>
        <span v-if="showAvatar" class="item__avatar"><img class="avatar" :src="`https://apic.douyucdn.cn/upload/${data.avatar}_small.jpg`" loading="lazy" /></span>
        <span :class="`item__name ${data.super==='5' ? 'super-name':'' }`">
            <span v-if="data.vip && showVip" class="Barrage-roomVipIcon"></span>
            {{data.nn}}：
        </span>
        <span :style="showColor?`color:${danmakuColor[data.color]};`:''" class="item__txt">{{data.txt}}</span>
    </div>
</template>

<script setup>
import {nobleData} from "@/global/utils/dydata/nobleData.js"
import {danmakuColor} from "@/global/utils/dydata/danmakuColor.js"
let props = defineProps(["data", "mode", "showAnimation", "showLevel", "showNoble", "showFans", "showDiamond", "showRoomAdmin", "showAvatar", "showVip", "showColor"])

// 控制日夜模式背景颜色
function getItemClass(data) {
    let ret = "";
    if (props.mode === "night") {
        if (data.nobleC || data.vip) {
            ret = "noble-night";
        }
        if (data.super == "5") {
            ret = "super-night";
        }
    } else {
        if (data.nobleC || data.vip) {
            ret = "noble-day";
        }
        if (data.super == "5") {
            ret = "super-day";
        }
    }
    return ret;
}
</script>

<style lang="scss" scoped>
@import "@/global/styles/themes/index.scss";
.item {
    vertical-align: middle;
    width: 100%;
    margin-bottom: 5px;
    padding: 0 4px;
    box-sizing: border-box;
    &:first-child {
        margin-top: 5px;
    }
    >* {
        margin-right: 5px;
    }
    >:nth-last-child(1), >:nth-last-child(2) {
        margin-right: 0;
    }
    .item__level {
        vertical-align: middle;
    }
    .item__fans {
        width: 60px;
        position: relative;
        vertical-align: middle;
    }

    .item__avatar {
        vertical-align: middle;
    }
    .item__name {
        vertical-align: middle;
        @include fontColor("nicknameColor");
    }
    .item__txt {
        vertical-align: middle;
        @include fontColor("txtColor");
    }
}
.noble-day {
    background-color:#fff3df;
    border-top:1px solid #ffe4b8;
    border-bottom:1px solid #ffe4b8;
}

.noble-night {
    background-color:rgb(55,55,55);
    border-top:1px solid rgb(90,90,90);
    border-bottom:1px solid rgb(90,90,90);
}

.super-day {
    background-color:#fae9ff;
    border-top:1px solid #ffe4b8;
    border-bottom:1px solid #ffe4b8;
}

.super-night {
    background-color:rgb(55, 45, 45);
    border-top:1px solid rgb(90,90,90);
    border-bottom:1px solid rgb(90,90,90);
}

.super-name {
    color: #fe5656 !important;
}
</style>

// remix/app/components/Danmaku/templates/Default/Default.tsx
import clsx from "clsx";
import type { FC } from "react";
import { danmakuColor } from "~/resources/danmakuColor";
import { nobleData } from "~/resources/nobleData";

interface IProps {
    // 弹幕数据
    data: IDanmaku;
    // 日夜间模式
    mode?: IMode;
    // 是否显示动画
    showAnimation?: boolean;
    // 是否显示用户等级
    showLevel?: boolean;
    // 是否显示贵族
    showNoble?: boolean;
    // 是否显示粉丝牌
    showFans?: boolean;
    // 是否显示钻粉
    showDiamond?: boolean; 
    // 是否显示房管图标
    showRoomAdmin?: boolean;
    // 是否显示用户头像
    showAvatar?: boolean;
    // 是否显示VIP图标
    showVip?: boolean;
    // 是否显示弹幕颜色
    showColor?: boolean;
    // 是否高亮
    isHighlight?: boolean;
}

const Default: FC<IProps> = (props) => {
    const {data} = props;
    const getItemClass = (data: IDanmaku): string => {
        if (data.isSuper) {
            return props.mode === "night" ? "super-night" : "super-day";
        } else if (data.isNoble || data.isVip || props.isHighlight) {
            return props.mode === "night" ? "noble-night" : "noble-day";
        } else {
            return "";
        }
    }
    return (
        <div className={clsx("item", {"fadeInLeft": props.showAnimation}, getItemClass(data))}>
            {/* 等级 */}
            {props.showLevel && <span className={clsx("item__level", {"fansLevelNight": props.mode==="night" && Number(data.lv) < 70}, "UserLevel", `UserLevel--${data.lv}`)}></span>}
            {/* 贵族 */}
            {props.showNoble && data.isNoble &&
            <span className="item__noble Barrage-icon Barrage-noble">
                <img src={`${data.nobleLv in nobleData.data ? nobleData.prefix + nobleData.data[data.nobleLv].pic : ""}`} alt="" loading="lazy"/>
            </span>}
            {/* 粉丝牌 */}
            {props.showFans && !!data.fansName &&
            <div className={clsx("item__fans", {"is-diamonds": data.isDiamond}, "FansMedal", `fansLevel-${data.fansLv}`)}>
                <span className="FansMedal-name">{data.fansName}</span>
                {/* 钻粉 */}
                {data.isDiamond && props.showDiamond && <img className="FansMedalBox-diamondsIcon" src="https://sta-op.douyucdn.cn/douyu/2021/08/05/02304a1c04587e43ac626ce5ce07d935.png" alt="" loading="lazy"/>}
            </div>}
            {/* 房管 */}
            {props.showRoomAdmin && data.isRoomAdmin &&
            <span className="item__roomAdmin">
                <span className="Barrage-icon Barrage-icon--roomAdmin"></span>
            </span>}
            {/* 头像 */}
            {props.showAvatar && <span className="item__avatar"><img className="avatar" src={`https://apic.douyucdn.cn/upload/${data.avatar}_small.jpg`} alt="" loading="lazy" /></span>}
            {/* 昵称 */}
            <span className={clsx("item__name", {"super-name": data.isSuper})}>
                {/* VIP */}
                {props.showVip && data.isVip && <span className="Barrage-roomVipIcon"></span>}
                {data.nn}：
            </span>
            {/* 弹幕 */}
            <span style={props.showColor ? {color: danmakuColor[data.color]} : {}} className="item__txt">{data.txt}</span>
        </div>
    )
}

export default Default;
