// remix/app/components/Enter/templates/Default/Default.tsx
import clsx from "clsx";
import type { FC } from "react";
import { Tag } from "react-vant";
import { nobleData } from "~/resources/nobleData";

interface IProps {
    // 进场数据
    data: IEnter;
    // 日夜间模式
    mode?: IMode;
    // 是否显示动画
    showAnimation?: boolean;
    // 是否显示用户等级
    showLevel?: boolean;
    // 是否显示贵族
    showNoble?: boolean;
    // 是否显示用户头像
    showAvatar?: boolean;
    // 是否高亮
    isHighlight?: boolean;
}

const Default: FC<IProps> = (props) => {
    const {data} = props;
    const getItemClass = (data: IEnter): string => {
        if (props.isHighlight) {
            return `highlight-${props.mode}`;
        }
        if (data.nobleLv) {
            return `noble-${props.mode}`;
        }
        return "";
    }
    return (
        <div className={clsx("item", {"fadeInLeft": props.showAnimation}, getItemClass(data))}>
            {/* 等级 */}
            {props.showLevel && <span className={clsx("item__level", {"fansLevelNight": props.mode==="night" && Number(data.lv) < 70}, "UserLevel", `UserLevel--${data.lv}`)}></span>}
            {/* 贵族 */}
            {props.showNoble && !!data.nobleLv && <span className="item__noble"><img src={`${data.nobleLv in nobleData.data ? nobleData.prefix + nobleData.data[data.nobleLv].pic : ""}`} loading="lazy" alt=""/></span>}
            {/* 头像 */}
            {props.showAvatar && <span className="item__avatar"><img className="avatar" src={`https://apic.douyucdn.cn/upload/${data.avatar}_small.jpg`} loading="lazy" alt=""/></span>}
            {/* 昵称 */}
            <span className="item__name"><span>{data.nn}</span> 进入了直播间</span>
        </div>
    )
}

export default Default;

// src/packages/Monitor/components/Enter/templates/Default.vue
<template>
    <div :class="`item ${showAnimation?'fadeInLeft' : ''} ${getItemClass(data)}`">
        <span v-if="showLevel" :class="`item__level ${mode==='night' && Number(data.lv) < 70 ?'fansLevelNight':''} UserLevel UserLevel--${data.lv}`"></span>
        <span v-if="!!data.noble && showNoble" class="item__noble"><img :src="`${data.noble in nobleData ? nobleData.prefix + nobleData[data.noble].pic : ''}`" loading="lazy"/></span>
        <span v-if="showAvatar" class="item__avatar"><img class="avatar" :src="`https://apic.douyucdn.cn/upload/${data.avatar}_small.jpg`" loading="lazy" /></span>
        <span class="item__name"><span>{{data.nn}}</span> 进入了直播间</span>
    </div>
</template>

<script setup>
import {nobleData} from "@/global/utils/dydata/nobleData.js"
let props = defineProps(["data", "mode", "keywords", "showAnimation", "showLevel", "showNoble", "showAvatar"]);

// 控制高亮以及日夜模式的背景色
function getItemClass(item) {
    let keywords = props.keywords.trim();
    if (keywords !== "") {
        let arr = keywords.split(" ");
        for (let i = 0; i < arr.length; i++) {
            if (item.nn.indexOf(arr[i]) !== -1) {
                if (props.mode === "night") {
                    return "highlight-night";
                } else {
                    return "highlight-day";
                }
            }
        }
    }
    if (item.noble) {
        if (props.mode === "night") {
            return "noble-night";
        } else {
            return "noble-day";
        }
    }
    return "";
}
</script>

<style lang="scss" scoped>
@import "@/global/styles/themes/index.scss";
.item {
    vertical-align: middle;
    width: 100%;
    margin-bottom: 5px;
    padding: 0 4px;
    box-sizing: border-box;
    &:first-child {
        margin-top: 5px;
    }
    >*{
        vertical-align: middle;
        margin-right: 5px;
    }

    .item__name {
        @include fontColor("contentColor");
        span {
            @include fontColor("nicknameColor");
        }
    }
}

.highlight-day {
    background-color:rgb(255,243,223);border-top:1px solid #ffe4b8;border-bottom:1px solid #ffe4b8;
}
.highlight-night {
    background-color: #494949;background-image: linear-gradient(90deg, #494949 0%, #9a9a9a 100%);
}

.noble-day {
    background-color:rgb(227,230,232);
}

.noble-night {
    background-color:rgb(55,55,55);border-top:1px solid rgb(90,90,90);border-bottom:1px solid rgb(90,90,90);
}
</style>
